from llm_sdk import Small_LLM_Model
from .schema import Schema
from .consumer import SchemaConsumer


class ConstrainedDecoder:
    """Generate function calls while enforcing Schema constraints."""

    # 150 is a safety limit chosen to give enough room for the function-call JSON 
    # while preventing unnecessarily long generation.
    # The decoder normally stops earlier as soon as the Schema reaches its finished state.

    def __init__(self, functions):
        self.model = Small_LLM_Model()
        self.functions = functions
        self.max_steps = 150

    def decode(self, prompt):

        # We're creating a new Schema object for this prompt.
        # ├── knows available functions
        # ├── knows the LLM
        # └── knows the user's prompt

        # We create a fresh Schema for every call to decode().
        # That's important because each prompt is a new generation.

        schema = Schema(
            self.functions,
            self.model,
            prompt,
        )

        consumer = SchemaConsumer(schema)

        # create an empty string called catalog tht will store the availables functions name
        # separated by new line
        # - fn_add_numbers: Add two numbers
        # - fn_greet: Greet a person
        # - fn_reverse_string: Reverse a string

        # The catalog is just a string containing the names and descriptions of all available functions,
        # which we give to the LLM as context.

        catalog = ""
        for name, function in self.functions.items():
            catalog += f"- {name}: {function.description}\n"

        # This is simply building the text that we will send to the LLM.
        # Choose the best function for the user's request.

        # Available functions:
        # - fn_add_numbers: Add two numbers
        # - fn_greet: Greet a person
        # - fn_reverse_string: Reverse a string

        # User request: Greet shrek

        # Generate the function call JSON.

        # The model_prompt only gives the model context and instructions.

        model_prompt = (
            f"Available functions:\n{catalog}\n\n"
            f"User request: {prompt}\n\n"
            "Generate the function call JSON."
        )

        # "encode() tokenizes the model prompt into token IDs.
        # squeeze() removes the unnecessary batch dimension, and
        # tolist() converts the tensor into a list
        # so we can append generated token IDs to it during decoding."

        context_ids = (
            self.model.encode(model_prompt)
            .squeeze(0)
            .tolist()
        )

        # This will store the token IDs generated by the decoder.
        result = []

        # We generate one token at a time.
        # the loop can execute at most 150 times.

        for _ in range(self.max_steps):

            # Before generating another token, we ask the Schema: "Is the function-call JSON complete?"
            # if yes we break ... so we have two main conditions to stop
            if schema.finished:
                break

            # We give the LLM all the tokens generated so far
            # The model produces a score for every possible token in its vocabulary.
            # These scores are the logits.
            # Higher score = the model considers that token more likely to be the next token.

            # We don't calculate the logits ourselves. The LLM calculates them. and returns a list of float logits

            allowed_ids = schema.allowed_tokens()

            if not allowed_ids:
                raise ValueError(
                    f"No valid tokens available in schema state "
                    f"{schema.state}"
                )

            if len(allowed_ids) == 1:
                # For the normal token case, we're mostly dealing with the 
                # fixed/structural parts of the JSON, such as: { : , } " But also things like function names,
                # parameter names, numbers, booleans, etc. depending on the current Schema state.
                token_id = allowed_ids[0]
            else:
                # get logits always return logits for all the vocablury
                # and iput its just a helper to define the context
                logits = self.model.get_logits_from_input_ids(context_ids)
                token_id = schema.select_token(logits, allowed_ids)
            # We add the chosen token ID to our generated result.
            result.append(token_id)

            # consume the token_id to update the schema state
            consumer.consume(token_id)

            # Contains the entire context given to the LLM, including the newly generated token.
            # Then the LLM uses that updated context to calculate the next logits.
            context_ids.append(token_id)

        # If we're here and Schema still isn't finished, it means:
        # We reached max_steps without producing a complete function call.

        if not schema.finished:
            raise RuntimeError(
                f"Constrained generation exceeded {self.max_steps} steps"
            )

        # We now convert those IDs back into text:
        return self.model.decode(result)
